### ISSUE TITLE
Please change IRC channel to something else

### ISSUE THREAD

**Issue by jonasbits** [Doichain/core#17]
https://github.com/Doichain/core/blob/afc64a0ddb1a3a5300e157d0abf66017ba447cb4/.travis.yml#L8

Namecoin is a open source project, so anybody is free to fork it, but please change the IRC channel that travis uses, we have no use for logs from your repo in our channel.

Best regards
Jonas

**Comment by inspiraluna** [comment]
Please take my deepest apologize!
